### ISSUE TITLE
怎么样可以使textview输入表情后也正常输入文字

### ISSUE THREAD

**Issue by hms040717007** [CCSH/SHEmotionKeyboard#1]

**Comment by hms040717007** [comment]
//点击表情方法
- (void)sendEmojiMsg:(NSString *)msg
           imageName:(nonnull NSString *)imageName {
    [self showWithText:msg];
    
    NSTextAttachment *attachment = [[NSTextAttachment alloc] init];
    attachment.image = [UIImage imageNamed:imageName];
    LJLog(@"imageNamed:%@",imageName);
                              
    attachment.bounds = CGRectMake(0, -5, 20, 20);

    NSMutableAttributedString *attachmentString = (NSMutableAttributedString *)[NSAttributedString attributedStringWithAttachment:attachment];
    [self.inputTextView.textStorage appendAttributedString:attachmentString];
}

//MARK:-----------------------------------------------------------------Delegate
- (void)textViewDidChange:(UITextView *)textView {
    //设置段落样式行间距
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.lineSpacing = kWIDTH_SCALE(15);// 字体的行间距
    
    NSDictionary *attributes = @{
                                 NSFontAttributeName:kSYSTEM_FONT(17),
                                 NSParagraphStyleAttributeName:paragraphStyle
                                 };
    
    textView.attributedText = [[NSAttributedString alloc] initWithString:textView.text
                                                              attributes:attributes];
}

**Comment by CCSH** [comment]
把我这个组件设置成输入框的inputview
