### ISSUE TITLE
你好，集成表情键盘之后 进去打开第一次 表情是全部重叠在一起的  第二次就好了 是什么原因呢？

### ISSUE THREAD

**Issue by thb1234** [CCSH/SHEmotionKeyboard#3]
你好，集成表情键盘之后 进去打开第一次 表情是全部重叠在一起的  第二次就好了 是什么原因呢？

![IMG_0246](https://user-images.githubusercontent.com/29907322/124746654-b52f7d00-df53-11eb-9bc6-35a60501cb77.jpg)
![IMG_0246](https://user-images.githubusercontent.com/29907322/124746653-b496e680-df53-11eb-98c0-fbb65e870b62.jpg)

**Comment by CCSH** [comment]
1.1.1修复了 我忘记发pod了

**Comment by thb1234** [comment]
好的  麻烦发一下  非常感谢

**Comment by thb1234** [comment]
谢谢大佬  非常好用

**Comment by CCSH** [comment]
看下pod更新到1.1.1了

**Comment by thb1234** [comment]
现在还是没搜索出来  最新的还是1.1.0

**Comment by CCSH** [comment]
有本地缓存吧，清一下

**Comment by CCSH** [comment]
![image](https://user-images.githubusercontent.com/16768967/124860088-a42e4c80-dfe3-11eb-836b-5f8ba698019e.png)

**Comment by thb1234** [comment]
好的 我清除下缓存



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 中午11:57
收件人: ***@***.***&gt;; 
抄送: "  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CCSH/SHEmotionKeyboard] 你好，集成表情键盘之后 进去打开第一次 表情是全部重叠在一起的  第二次就好了 是什么原因呢？ (#3)

**Comment by thb1234** [comment]
已经更新了  没有问题了   感谢大佬抽空解决
